version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
platform: Win32
shallow_clone: true
build_script:
- cmd: >-
    appveyorbuild.cmd Win32!Release
artifacts:
- path: Build/WinMerge/Win32/Release
